name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          ls -la ./src 
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-app-go:${{ github.sha }} ./src
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-app-go:${{ github.sha }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters list
          gcloud container clusters get-credentials optimized-cluster \
            --zone ${{ secrets.GCP_ZONE }} \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/node-app-go \
            node-app-go=gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-app-go:${{ github.sha }}